import type { Metadata } from "next";
import { Geist, Geist_Mono, BIZ_UDPGothic } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";

const bizUdpGothic = BIZ_UDPGothic({
  weight: ["400", "700"],
  subsets: ["latin"],
  display: "swap",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${bizUdpGothic.className} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
